### ISSUE TITLE
Autotokenizer fails "out of the box"

### ISSUE THREAD

**Issue by topotech** [unb-cic-esw/facebook-page-post-scraper#119]
## 1. Description

The scrapper doesn't work out of the box because there is an invalid `config.ini` in `./scraper`.

## 2. Reproduction of the problem

1. Clone the git
2. Create venv
3. Install all dependencies
4. run `make autotoken`
5. Get error.

## 3. Comportamento esperado

The Token Manager runs `check_semi_automatic_collection()` successfully instead of running `check_automatic_collection('config.ini')` with an error.

## Comments

The fix is so trivial that I think that maybe you did it intentionally so less people abuses your script. If that's the case, consider this solved.

**Comment by alexandrebarbaruiva** [comment]
Actually, this issue hadn't been reported to us during our development cycle. The facebook API does a nice job preventing any case of abuse (at least it did during the Cambridge Analytica scandal). We'd be happy to have your feedback on using the script!

**Comment by alexandrebarbaruiva** [comment]
@topotech feel free to contact me at telegram, my username is the as here
