### ISSUE TITLE
Autotokenizer failed

### ISSUE THREAD

**Issue by sieverett** [unb-cic-esw/facebook-page-post-scraper#33]
I ran 'make autotoken' with Y and got success messages:

But then ran 'make' to test the install and got errors (pasted below).  

I tried to see if I could run 'make autotoken' again with 'N'. I got these messages:

"Wrong User Login
Auto Token function Failed!" 

I did this a few times (and experimented with token versions 2.12 and 3.0, and also made sure i had correct login info.

stdout from 'make' test:
test_page_scraper
  TestPageScraperBasics
.   Check if page provided by user is correctly stored. Example used is Github's page
.   Check if token provided by user hasn't expired
  TestPageScraping
.   Check if when presented with a invalid page get_reactions returns an error message
.   Check if when presented with a page content, csv converter generates a csv file with the proper content
.   Check if when presented with no content, csv converter returns a 'No content found' instead of an empty csv
.   test_if_get_reactions_works
.   test_if_get_reactions_works_with_more_pages
.   Check if when presented with multiple page contents, csv converter generates only one csv file with the proper content of all pages and without duplicated pages
.   Check if scraping generates a JSON file in correct output file
.   Check if scraping is correct and working
.   Check if scraping with queries is correct and working correctly
.   Check if the page validation is working
.   Check if it's possible to collect name and like from LearnPython page with date of collection
.   Check if when user doesn't define page, program returns warning
test_token_manager
  TestTokenCollection
F   test_check_function_for_automatic_token
F   test_check_function_for_semi_automatic_token
.   test_collect_token
F   test_collect_token_automatically_with_correct_id
.   test_collect_token_automatically_with_wrong_id
.   test_collect_token_automatically_without_internet
  TestTokenCollectionWithBrowser
    test_check_function_for_manual_token
.   test_check_function_for_manual_token
.   test_collect_token_manually
  TestTokenFunctions
.   Check if token file generation is generating a correct file
.   Check if token file can be generated
.   Check if token file can be updated with new token
.   Check if token file exists, if it doesn't, returns warning message
.   Check if token file is well formatted
  TestTokenSecurity
.   test_decrypt_user_password
.   test_encrypt_user_password
E   test_get_user_password_decrypted
.   test_get_user_password_decrypted_no_token
.   test_if_token_can_be_updated_with_password
F   test_if_token_has_password

Captured stdout for test_page_scraper.TestPageScraping.test_if_csv_without_content_returns_nothing
'str' object has no attribute 'keys'

Captured stdout for test_page_scraper.TestPageScraping.test_if_get_reactions_works_with_more_pages
100 Statuses Processed: 2018-05-21 10:20:53.673130
100 Statuses Processed: 2018-05-21 10:20:57.257912

Captured stdout for test_page_scraper.TestPageScraping.test_scraping_without_page
'Scraper' object has no attribute 'page'

Captured stdout for test_token_manager.TestTokenCollection.test_collect_token
No token detected.

Captured stdout for test_token_manager.TestTokenCollection.test_collect_token_automatically_with_wrong_id
Wrong User Login

Captured stdout for test_token_manager.TestTokenCollectionWithBrowser.test_check_function_for_manual_token
1. Login on your Facebook Account
2. Click on "Get token" then "Get User Access Token".
3. Then select "manage_pages","publish_pages",
"pages_show_list" and "pages_manage_instant_articles".
4. Finish by clicking on "Get Access Token".

Now paste your user Access Token here:
New token written successfuly.

Set Token is not Valid

Auto Token function Completed

Captured stdout for test_token_manager.TestTokenCollectionWithBrowser.test_collect_token_manually
New token written successfuly.

Captured stdout for test_token_manager.TestTokenFunctions.test_if_token_file_can_be_updated
File not updated.
New token written successfuly.

Captured stdout for test_token_manager.TestTokenSecurity.test_decrypt_user_password
'bytes' object has no attribute 'encode'
'bytes' object has no attribute 'encode'

Captured stdout for test_token_manager.TestTokenSecurity.test_get_user_password_decrypted_no_token
Token file not found. decrypt_user_password() argument after ** must be a mapping, not bool

Failure in test_token_manager.TestTokenCollection.test_check_function_for_automatic_token
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/silas/aws/elastic/pyelfacebook/facebook-page-post-scraper/tests/test_token_manager.py", line 204, in test_check_function_for_automatic_token
    self.fail('No user/password informed. Use autotoken.')
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: No user/password informed. Use autotoken.

Failure in test_token_manager.TestTokenCollection.test_check_function_for_semi_automatic_token
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/silas/aws/elastic/pyelfacebook/facebook-page-post-scraper/tests/test_token_manager.py", line 214, in test_check_function_for_semi_automatic_token
    self.fail('No user/password informed. Use autotoken.')
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: No user/password informed. Use autotoken.

Failure in test_token_manager.TestTokenCollection.test_collect_token_automatically_with_correct_id
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/silas/aws/elastic/pyelfacebook/facebook-page-post-scraper/tests/test_token_manager.py", line 185, in test_collect_token_automatically_with_correct_id
    self.fail('No user/password informed. Use autotoken.')
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: No user/password informed. Use autotoken.

Error in test_token_manager.TestTokenSecurity.test_get_user_password_decrypted
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/silas/aws/elastic/pyelfacebook/facebook-page-post-scraper/tests/test_token_manager.py", line 128, in test_get_user_password_decrypted
    type(decrypt_user_password(**retrieve_password_file()))
TypeError: decrypt_user_password() argument after ** must be a mapping, not bool

Captured stdout for test_token_manager.TestTokenSecurity.test_get_user_password_decrypted
Token file not found. decrypt_user_password() argument after ** must be a mapping, not bool

Failure in test_token_manager.TestTokenSecurity.test_if_token_has_password
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/silas/aws/elastic/pyelfacebook/facebook-page-post-scraper/tests/test_token_manager.py", line 91, in test_if_token_has_password
    self.fail('No user/password informed. Use autotoken.')
  File "/home/silas/anaconda3/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: No user/password informed. Use autotoken.

Ran 33 tests in 29.984s

FAILED (errors=1, failures=4, passes=28)
makefile:19: recipe for target 'test' failed
make: *** [test] Error 1

**Comment by alexandrebarbaruiva** [comment]
Could you delete the `config.ini` file and try `make autotoken` with N again?

**Comment by sieverett** [comment]
The error persisted after deleting the config.ini.enc file and trying to make autotoken with N.  I will try logging out of FB account on browser before trying again.  Any other ideas?

**Comment by sieverett** [comment]
Logging out of FB before making autotoken didn't fix the error. Still received:
Wrong User Login
Auto Token function Failed!

**Comment by alexandrebarbaruiva** [comment]
You have to delete the `config.ini` located on your `scraper`folder`, the `config.ini.enc` file was just to check if all tests on the program were correct.

**Comment by trosemberg** [comment]
could you please try again and give us a feedback of what happend? We believe we fixed the bug and added an english version of the readme

**Comment by sieverett** [comment]
Nice! thanks for your prompting. It's working now.  I'll let you know if i get stuck.
