### ISSUE TITLE
Problema para abrir no excel os dados coletados

### ISSUE THREAD

**Issue by trosemberg** [unb-cic-esw/facebook-page-post-scraper#70]
## Descreva o bug

Ao tentar abrir os dados coletados utilizando o programa Microsoft Excel, gera-se uma tabela com
apenas uma coluna, tornando inviável a visualização dos dados coletados.

## Para reproduzir

Passos para reproduzir o comportamento:

1. Rode o programa utilizando o comando `make run`
2. Abra o arquivo resultante de extensão ".csv" usando o programa Microsoft Excel   
3. Veja o erro

## Comportamento esperado

O Comportamento esperado seria uma separação das informações em colunas onde as
vírgulas se encontram.

**Comment by trosemberg** [comment]
Para resolução do problema, basta selecionar a primeira coluna do Excel, onde se encontram
todas as informações selecionar a aba "Dados" e clicar em "Texto para Colunas" conforme mostrado
na figura a seguir:
![image](https://user-images.githubusercontent.com/31709590/41888538-61b89fb6-78dc-11e8-8f97-cd990f1747a5.png)
A partir disso, selecionar para usar ","(vírgulas) como divisão entre colunas e o excel
transformará o arquivo no formato desejado para melhor visualização.

**Comment by alexandrebarbaruiva** [comment]
issue resolvida com o comentário acima do @trosemberg
